Fixed artifact upload.

diff --git a/bin/build-openca-devenv b/bin/build-openca-devenv
--- a/bin/build-openca-devenv
+++ b/bin/build-openca-devenv
@@ -5,7 +5,14 @@ echo "(c) Massimiliano Pala and OpenCA Labs"
 echo "All Rights Reserved"
 echo
 
+# TODAY's DATE
+TODAY=$(date +%Y%m%d)
+
+# DEV BUILD FLAG
+TAG_DEVENV="devenv"
+
 if [ "$1" = "" ] ; then
+
   echo "ERROR: Missing required parameter (image name)"
   echo
   echo "    USAGE: $0 [ ubuntu24 | ubuntu24-crypto | ubuntu24-libpki ] [ y | n ] [ no-cache ]"
@@ -14,6 +21,28 @@ if [ "$1" = "" ] ; then
   echo "to force the pushing of the image to the official repository on CodeLab."
   echo
   exit 1
+
+else
+
+  case "$1" in
+    ubuntu24)
+        TAG_DEVENV="devenv"
+      ;;
+    ubuntu24-crypto)
+        TAG_DEVENV="devenv-crypto"
+      ;;
+    ubuntu24-libpki)
+        TAG_DEVENV="devenv-libpki"
+      ;;
+    *)
+      echo "ERROR: Invalid image name [$1]"
+      echo
+      echo "    USAGE: $0 [ ubuntu24 | ubuntu24-crypto | ubuntu24-libpki ] [ y | n ] [ no-cache ]"
+      echo
+      exit 1
+      ;;
+  esac
+
 fi
 
 if [ "$2" = "yes" -o "$2" = "y" -o "$2" = "Y" ] ; then
@@ -26,17 +55,14 @@ if [ "$3" = "no-cache" -o "$2" = "no-cache" ] ; then
   NO_CACHE_OPT="--no-cache"
 fi
 
-# TODAY's DATE
-TODAY=$(date +%Y%m%d)
-
 # TAGS
-# export TAG_BASE_URL=openca.org
-export TAG_BASE_URL=ghcr.io/openca
-export DOCKER_FILE="Docker/Dockerfile.$1"
-export OPTS="--build-arg DEV_BUILD=${DEV_BUILD} $NO_CACHE_OPT"
-export TAG_IMAGE_BASE=$TAG_BASE_URL/$1
-export TAG_IMAGE_LATEST=$TAG_IMAGE_BASE:latest
-export TAG_IMAGE_DATE=$TAG_IMAGE_BASE:$TODAY
+# TAG_BASE_URL=openca.org
+TAG_BASE_URL=ghcr.io/openca
+DOCKER_FILE="Docker/Dockerfile.$1"
+OPTS="--build-arg DEV_BUILD=${DEV_BUILD} $NO_CACHE_OPT"
+TAG_IMAGE_BASE=$TAG_BASE_URL/$1
+TAG_IMAGE_LATEST=$TAG_IMAGE_BASE:latest
+TAG_IMAGE_DATE=$TAG_IMAGE_BASE:$TODAY
 
 # Some Info
 echo "* Building Image from Dockerfile.$1 ..."
@@ -46,7 +72,14 @@ echo
 
 # Build the image
 docker build $NO_CACHE_OPT $OPTS -f "$DOCKER_FILE" \
-  -t "$TAG_IMAGE_LATEST" -t "$TAG_IMAGE_DATE" .
+  -t "$TAG_IMAGE_LATEST" -t "$TAG_IMAGE_DATE" . 2>&1 | \
+    tee build-openca-devenv.log
+
+# Checks if we have the DEVENV tag to be applied
+if ! [ "$TAG_DEVENV" = "" ] ; then
+  docker tag "$TAG_IMAGE_LATEST" "$TAG_BASE_URL/$TAG_DEVENV:latest"
+  docker tag "$TAG_IMAGE_DATE" "$TAG_BASE_URL/$TAG_DEVENV:$TODAY"
+fi
 
 # Checks the result and aborts on error
 if [ $? -gt 0 ] ; then
